#!/bin/sh
#
# 50-asterisk-seed-conf
#
# Defined in Dockerfile:
# DOCKER_CONF_DIR DOCKER_SEED_CONF_DIR
#

#
# If DOCKER_CONF_DIR is empty, initialize it with files from
# DOCKER_SEED_CONF_DIR. We don't want to overwrite any files,
# but we only have "cp -u" (only copy newer) in busybox.
# The directory should be empty when we try to copy,
# so this is just an extra precaution.
#
if [ -z "$(ls -A $DOCKER_CONF_DIR 2>/dev/null)" ]; then
	dc_log 5 "Seeding asterisk configuration."
	cp -p -u $DOCKER_SEED_CONF_DIR/* $DOCKER_CONF_DIR
fi
