#!/bin/sh
#
# 50-asterisk-seed-conf
#
#
#
source docker-common.sh

DOCKER_CONF_DIR=${DOCKER_CONF_DIR-/etc/asterisk}
DOCKER_SEED_CONF_DIR=${DOCKER_SEED_CONF_DIR-/usr/local/share/astrisk/config}


#
# Make sure that we have the required directory structure in place under
# DOCKER_PERSIST_DIR. It will be missing if we mount an empty volume there.
#
mkdir -p ${DOCKER_PERSIST_DIR}${DOCKER_SPOOL_DIR} \
	${DOCKER_PERSIST_DIR}${DOCKER_CONF_DIR} \
	${DOCKER_PERSIST_DIR}${DOCKER_LOG_DIR} \
	${DOCKER_PERSIST_DIR}${DOCKER_MOH_DIR}

#
# If DOCKER_CONF_DIR is empty, initialize it with files from
# DOCKER_SEED_CONF_DIR. We don't want to overwrite any files,
# but we only have "cp -u" (only copy newer) in busybox.
# The directory should be empty when we try to copy,
# so this is just an extra precaution.
#
if [ -z "$(ls -A $DOCKER_CONF_DIR 2>/dev/null)" ]; then
	dc_log 5 "Seeding asterisk configuration."
	cp -p -u $DOCKER_SEED_CONF_DIR/* $DOCKER_CONF_DIR
fi
