#!/bin/sh
#
# 10-acme-common
#
# Define variables and functions used during container initialization.
#
# Variables defined in Dockerfile
# DOCKER_ACME_SSL_DIR DOCKER_APPL_SSL_DIR
#
ACME_FILE=${ACME_FILE-/acme/acme.json}
HOSTNAME=${HOSTNAME-$(hostname)}
DOMAIN=${HOSTNAME#*.}
DOCKER_APPL_SSL_CERT=${DOCKER_APPL_SSL_CERT-$DOCKER_APPL_SSL_DIR/cert.pem}
DOCKER_APPL_SSL_KEY=${DOCKER_APPL_SSL_KEY-$DOCKER_APPL_SSL_DIR/priv_key.pem}
DOCKER_ACME_SSL_H_CERT=$DOCKER_ACME_SSL_DIR/certs/${HOSTNAME}.crt
DOCKER_ACME_SSL_H_KEY=$DOCKER_ACME_SSL_DIR/private/${HOSTNAME}.key
DOCKER_ACME_SSL_D_CERT=$DOCKER_ACME_SSL_DIR/certs/${DOMAIN}.crt
DOCKER_ACME_SSL_D_KEY=$DOCKER_ACME_SSL_DIR/private/${DOMAIN}.key

#
# Setup monitoring of ACME_FILE
#
acme_monitor_tls_cert() {
	if (dc_is_installed jq && (dc_is_command inotifyd || dc_is_command inotifywait)); then
		if [ -s $ACME_FILE ]; then
			# run acme-extract.sh on cnt creation (and every time the json file changes)
			dc_log 5 "Setup ACME TLS certificate monitoring"
			if dc_is_command inotifyd; then
				docker-service.sh "-n acme $(which inotifyd) $(which acme-extract.sh) $ACME_FILE:c"
			else
				docker-service.sh "-n acme sh -c \"while $(which inotifywait) -e close_write $ACME_FILE; do $(which acme-extract.sh); done\""
			fi
			# acme-extract.sh reports to logger but it is yet to be started so this run will be quiet
			acme-extract.sh $ACME_FILE $DOCKER_ACME_SSL_DIR
		fi
	else
		dc_log 5 "Not all required pkgs installed so cannot setup ACME TLS certificate monitoring"
	fi
}

#
# Arrange sym-links to support both host and domain certificates.
#
acme_symlink_tls_cert() {
	if ([ -r $DOCKER_ACME_SSL_H_CERT ] && [ -r $DOCKER_ACME_SSL_H_KEY ]); then
		dc_log 5 "Setting up ACME TLS certificate for host $HOSTNAME"
		mkdir -p $DOCKER_APPL_SSL_DIR
		ln -sf $DOCKER_ACME_SSL_H_CERT $DOCKER_APPL_SSL_CERT
		ln -sf $DOCKER_ACME_SSL_H_KEY $DOCKER_APPL_SSL_KEY
	else
		if ([ -r $DOCKER_ACME_SSL_D_CERT ] && [ -r $DOCKER_ACME_SSL_D_KEY ]); then
			dc_log 5 "Setting up ACME TLS certificate for domain $DOMAIN"
			mkdir -p $DOCKER_APPL_SSL_DIR
			ln -sf $DOCKER_ACME_SSL_D_CERT $DOCKER_APPL_SSL_CERT
			ln -sf $DOCKER_ACME_SSL_D_KEY $DOCKER_APPL_SSL_KEY
		fi
	fi
}
