#!/bin/sh
#
# 10-acme-common
#
# Define variables and functions used during container initialization.
#
# Variables defined in Dockerfile
# DOCKER_ACME_SSL_DIR DOCKER_APPL_SSL_DIR
#
ACME_FILE=${ACME_FILE-/acme/acme.json}
HOSTNAME=${HOSTNAME-$(hostname)}
DOMAIN=${HOSTNAME#*.}
DOCKER_ACME_SSL_H_CERT=$DOCKER_ACME_SSL_DIR/certs/${HOSTNAME}.crt
DOCKER_ACME_SSL_H_KEY=$DOCKER_ACME_SSL_DIR/private/${HOSTNAME}.key
DOCKER_ACME_SSL_D_CERT=$DOCKER_ACME_SSL_DIR/certs/${DOMAIN}.crt
DOCKER_ACME_SSL_D_KEY=$DOCKER_ACME_SSL_DIR/private/${DOMAIN}.key
DOCKER_APPL_SSL_CERT=$DOCKER_APPL_SSL_DIR/cert.pem
DOCKER_APPL_SSL_KEY=$DOCKER_APPL_SSL_DIR/priv_key.pem

#
# Setup monotoring of ACME_FILE
#
acme_monitor_tls_cert() {
	if (dc_is_installed jq && [ -s $ACME_FILE ]); then
		dc_log 5 "Setup ACME TLS certificate monitoring"
		docker-service.sh "-n acme $(which inotifyd) $(which acme-extract.sh) $ACME_FILE:c"
		# run acme-extract.sh on cnt creation (and every time the json file changes)
		# acme-extract.sh reports to logger but it is yet to be started so this run will be quiet
		acme-extract.sh $ACME_FILE $DOCKER_ACME_SSL_DIR
	fi
}

#
# Arrange sym-links to support both host and domain certificates.
#
acme_symlink_tls_cert() {
	if ([ -r $DOCKER_ACME_SSL_H_CERT ] && [ -r $DOCKER_ACME_SSL_H_KEY ]); then
		dc_log 5 "Seting up ACME TLS certificate for host $HOSTNAME"
		ln -sf $DOCKER_ACME_SSL_H_CERT $DOCKER_APPL_SSL_CERT
		ln -sf $DOCKER_ACME_SSL_H_KEY $DOCKER_APPL_SSL_KEY
	else
		if ([ -r $DOCKER_ACME_SSL_D_CERT ] && [ -r $DOCKER_ACME_SSL_D_KEY ]); then
			dc_log 5 "Seting up ACME TLS certificate for domain $DOMAIN"
			ln -sf $DOCKER_ACME_SSL_D_CERT $DOCKER_APPL_SSL_CERT
			ln -sf $DOCKER_ACME_SSL_D_KEY $DOCKER_APPL_SSL_KEY
		fi
	fi
}
