#!/bin/sh
#
# 50-autoban-read-nftfile
#
# Load NFT state from file.
#

#
# Configuration
# The templates are in /usr/share/nftables and the actual state file is kept
# in /etc/nftables.d.
#
source docker-common.sh

DOCKER_NFT_DIR=${DOCKER_NFT_DIR-/etc/nftables.d}
DOCKER_SEED_NFT_DIR=${DOCKER_SEED_NFT_DIR-/usr/share/nftables}
DOCKER_NFT_FILE=${DOCKER_NFT_FILE-autoban.nft}
DOCKER_NFT_TABLE=${DOCKER_NFT_TABLE-autoban}

#
# Only proceed if nftables is installed
#

if ! dc_is_installed nftables; then
	dc_log 5 "Not possible to seed nft configuration since nftables is not installed."
	return
fi

#
# Make sure that we have the required directory structure in place under
# DOCKER_PERSIST_DIR. It will be missing if we mount an empty volume there.
#

mkdir -p ${DOCKER_PERSIST_DIR}${DOCKER_NFT_DIR}

#
# If DOCKER_NFT_FILE is empty or is missing
# initialize it with files from DOCKER_SEED_NFT_DIR.
#

nft_file=$DOCKER_NFT_DIR/$DOCKER_NFT_FILE

if [ ! -s ${nft_file} ]; then
	dc_log 5 "Seeding nft configuration."
	cp $DOCKER_SEED_NFT_DIR/$DOCKER_NFT_FILE $DOCKER_NFT_DIR
fi

#
# If nft_file exists have NFT import it
#

if [ -f ${nft_file} ]; then
	dc_log 5 "Importing $nft_file."
	if nft delete table $DOCKER_NFT_TABLE 2>/dev/null; then
		dc_log 4 "nft table $DOCKER_NFT_TABLE was overwritten"
	fi
	nft -f ${nft_file}
fi
