#!/bin/sh
#
# 50-autoban-write-nftfile
#
# Save current NFT state to file.
#

#
# Configuration
# The templates are in /usr/share/nftables and the actual state file is kept
# in /etc/nftables.d.
#
source docker-common.sh

DOCKER_NFT_DIR=${DOCKER_NFT_DIR-/etc/nftables.d}
DOCKER_NFT_FILE=${DOCKER_NFT_FILE-autoban.nft}
DOCKER_NFT_TABLE=${DOCKER_NFT_TABLE-autoban}

#
# Only proceed if nftables is installed
#

if ! dc_is_installed nftables; then
	dc_log 5 "Not possible to save nft state since nftables is not installed."
	return
fi

#
# Save current nftables state to file. Omit any "expires time-string" by using
# the option --stateless, since nftables refuse to load files with them.
#

nft_file=$DOCKER_NFT_DIR/$DOCKER_NFT_FILE
if [ -n ${nft_file} ]; then
	dc_log 5 "Saving config to $nft_file."
	nft --stateless list table $DOCKER_NFT_TABLE > ${nft_file}
fi
