#!/bin/sh
#
# 50-autoban-write-nftfile
#
# Save current NFT state to file.
#

#
# Configuration
# Note that the templates are in /etc/nftables and the actual state file is kept
# in /var/lib/nftables, which might be perceived to be counter intuitive.
#
source docker-common.sh

DOCKER_NFT_DIR=${DOCKER_NFT_DIR-/var/lib/nftables}
DOCKER_SEED_NFT_DIR=${DOCKER_SEED_NFT_DIR-/etc/nftables}
DOCKER_NFT_FILE=${DOCKER_NFT_FILE-autoban.nft}
DOCKER_NFT_TABLE=${DOCKER_NFT_TABLE-autoban}

#
# Only proceed if nftables is installed
#

if ! dc_is_installed nftables; then exit; fi

#
# Save current NFT state to file. Omit any "expires time-string" by using
# the option --stateless, since NFT refuse to load files with them.
#

nft_file=$DOCKER_NFT_DIR/$DOCKER_NFT_FILE
if [ -n "$nft_file" ]; then
	dc_log 5 "Saving config to $nft_file."
	nft --stateless nft list table $DOCKER_NFT_TABLE > ${nft_file}
#	nft list ruleset | sed 's/expires [[:alnum:]]*//g' > ${nft_file}
fi
