#!/bin/sh
#
# 50_nft-save
#
#
#
DOCKER_NFT_DIR=${DOCKER_NFT_DIR-/var/lib/nftables}
DOCKER_SEED_NFT_DIR=${DOCKER_SEED_NFT_DIR-/etc/nftables}
DOCKER_NTF_FILE=${DOCKER_NTF_FILE-autoban.nft}

#
# Save current ntf state to file. Remove any "expires timesrt" since nfs refuse
# to load files with them.
#
nft_file=$DOCKER_NFT_DIR/$DOCKER_NTF_FILE
if [ -n "$nft_file" ]; then
	printf "entrypoint[$$]: INFO:$(basename $0): nftables saving config to $nft_file.\n"
	nft list ruleset | sed 's/expires [[:alnum:]]*//g' > ${nft_file}
fi
