#!/bin/bash
# hooks/build
# $DOCKER_REPO and $DOCKER_TAG are injected into the build environment

#
# Identify build target
#
echo "hooks/build called with IMAGE_NAME=${DOCKER_REPO}:${DOCKER_TAG}, so we will run:"
case "${DOCKER_TAG}" in
	mini*)                bld_target=mini ;;
	base*)                bld_target=base ;;
	full*|latest*|[0-9]*) bld_target=full ;;
	xtra*)                bld_target=xtra ;;
	*)
		echo "NOTHING since we do not know how to build with tag=${DOCKER_TAG}"
		exit 1
	;;
esac

#
# Build image
#
echo "docker build --target $bld_target -t ${DOCKER_REPO}:${DOCKER_TAG} ."
docker build --target $bld_target -t ${DOCKER_REPO}:${DOCKER_TAG} .
