#!/bin/bash
# hooks/pre_build
# $DOCKER_REPO and $DOCKER_TAG are injected into the docker hub build environment

#
# Explore the docker hub build environment
#
uname -a || true
for utility in apt dpkg curl wget; do
	which $utility || true
done
printenv || true

#
# make pre_build
#
make make pre_build
