#!/bin/sh
#
# 50_setup-tlscert-acme
#
#
#

#
# Config
#

ACME_FILE=${ACME_FILE-/acme/acme.json}
HOSTNAME=${HOSTNAME-$(hostname)}
DOCKER_ACME_SSL_DIR=${DOCKER_ACME_SSL_DIR-/etc/ssl/acme}
DOCKER_AST_SSL_DIR=${DOCKER_AST_SSL_DIR-/etc/ssl/asterisk}

#
# Helpers
#

inform() { printf "entrypoint[$$]: INFO:$(basename $0): $*.\n" ;}

_is_installed() { apk -e info $1 &>/dev/null ;} # true if pkg is installed

#
# Make sure that we have the required directory structure in place under
# DOCKER_PERSIST_DIR. It will be missing if we mount an empty volume there.
#

fix_persist_dirs() {
	mkdir -p ${DOCKER_PERSIST_DIR}${DOCKER_AST_SSL_DIR} \
		${DOCKER_PERSIST_DIR}${DOCKER_ACME_SSL_DIR}
}

setup_runit_acme_dump() {
	if (_is_installed jq && [ -s $ACME_FILE ]); then
		inform "Setup ACME TLS certificate monitoring"
		setup-runit.sh "-n acme $(which inotifyd) $(which dumpcerts.sh) $ACME_FILE:c"
		# run dumpcerts.sh on cnt creation (and every time the json file changes)
		local message="$(dumpcerts.sh $ACME_FILE $DOCKER_ACME_SSL_DIR 2>&1 | sed ':a;N;$!ba;s/\n/ - /g')"
		inform "$message"
	fi
}

setup_acme_tls_cert() {
	local cert=$DOCKER_AST_SSL_DIR/asterisk.cert.pem
	local key=$DOCKER_AST_SSL_DIR/asterisk.priv_key.pem
	if ([ -s $ACME_FILE ] && ([ ! -s $cert ] || [ ! -s $key ])); then
		inform "Setup ACME TLS certificate for host $HOSTNAME"
		ln -sf $DOCKER_ACME_SSL_DIR/certs/${HOSTNAME}.crt $cert
		ln -sf $DOCKER_ACME_SSL_DIR/private/${HOSTNAME}.key $key
	fi
}

#
# Run
#

fix_persist_dirs
setup_runit_acme_dump
setup_acme_tls_cert
