#!/bin/sh
#
# 50-docker-update-loglevel
#
# If SYSLOG_LEVEL is not empty update syslog level
#
source docker-common.sh

if [ -n "$SYSLOG_LEVEL" ]; then
	dc_log 5 "Setting syslogd level=$SYSLOG_LEVEL."
	setup-runit.sh "syslogd -nO- -l$SYSLOG_LEVEL $SYSLOG_OPTIONS"
fi
